self.transport.resumeProducing() will no longer raise an AssertionError if called after self.transport.loseConnection()